"""
APRIL Bilateral Facilities Register
=====================================
Python/Dash equivalent of the APRIL Bilateral Facilities HTML app.
As at 02 June 2026 | Banking Facilities Overview across HK, SG & UAE

Requirements:
    pip install dash pandas

Run:
    python april_bilateral_facilities.py
Then open http://127.0.0.1:8050 in your browser.
"""

import pandas as pd
import dash
from dash import dcc, html, Input, Output, dash_table
import dash_bootstrap_components as dbc

# ---------------------------------------------------------------------------
# DATA
# ---------------------------------------------------------------------------

RAW_DATA = [
    {
        "bankName": "Bank of China (Hong Kong) Limited",
        "location": "HK",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "11/09/2018 amended on 20/03/2024",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 11/09/18",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "Bank of China (Hong Kong) Limited",
        "location": "HK",
        "borrower": "AFPT",
        "borrowerList": ["AFPT"],
        "dateOfFacility": "26/11/2024",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "Bank of China (Hong Kong) Limited",
        "location": "HK",
        "borrower": "AIE, AFPT, IWC, ASHK, ASCH",
        "borrowerList": ["AIE", "AFPT", "IWC", "ASHK", "ASCH"],
        "dateOfFacility": "28/05/2025",
        "currency": "USD",
        "quantum": "85,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "Bank of China, Macau branch",
        "location": "HK",
        "borrower": "ICL",
        "borrowerList": ["ICL"],
        "dateOfFacility": "01/03/2024",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "Bank of China, Macau branch",
        "location": "HK",
        "borrower": "ASCH",
        "borrowerList": ["ASCH"],
        "dateOfFacility": "01/04/2025",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "Bank of Communications, HK",
        "location": "HK",
        "borrower": "IWC",
        "borrowerList": ["IWC"],
        "dateOfFacility": "3/10/16, amended on 8/12/17, 1/3/19, 10/1/20, 22/3/23",
        "currency": "USD",
        "quantum": "70,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 13/10/16",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "Bank of East Asia, HK",
        "location": "HK",
        "borrower": "ASCH, ASHK",
        "borrowerList": ["ASCH", "ASHK"],
        "dateOfFacility": "25/11/2024",
        "currency": "USD",
        "quantum": "18,000,000\n2,000,000",
        "facilityType": "Trade Finance, Derivatives",
        "facilityTypeList": ["Trade Finance", "Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 20/05/2024",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "Bank Sinopac, HK",
        "location": "HK",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "Negotiating",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Negotiating",
        "securityPackage": "Negotiating",
        "guarantorList": [],
    },
    {
        "bankName": "Cathay United Bank",
        "location": "HK",
        "borrower": "ASHK, AIE",
        "borrowerList": ["ASHK", "AIE"],
        "dateOfFacility": "09/09/2025",
        "currency": "USD",
        "quantum": "15,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 09/09/25",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "Cathay United Bank",
        "location": "HK",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "03/10/2025",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 3/10/25",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "Changhwa Commercial Bank",
        "location": "HK",
        "borrower": "AFPT",
        "borrowerList": ["AFPT"],
        "dateOfFacility": "27/8/2024 amended on 29/07/25",
        "currency": "USD",
        "quantum": "30,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "30/06/2025",
        "tenureExpired": True,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 03/09/24",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "China CITIC Bank International Limited",
        "location": "HK",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "16/7/2020, amended on 26/06/23",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 16/07/20",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "China CITIC Bank International Limited",
        "location": "HK",
        "borrower": "ASCH",
        "borrowerList": ["ASCH"],
        "dateOfFacility": "07/12/2017",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 21/07/21",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "China CITIC Bank International Limited",
        "location": "HK",
        "borrower": "ASHK , IWC, ASCH, AIE, GGTMCO AFEM, AFPT",
        "borrowerList": ["ASHK", "IWC", "ASCH", "AIE", "GGTMCO AFEM", "AFPT"],
        "dateOfFacility": "12/6/2021\nISDA dd 16/07/2020 amended on 26/06/2023",
        "currency": "USD",
        "quantum": "80,000,000",
        "facilityType": "Trade Finance, Derivatives",
        "facilityTypeList": ["Trade Finance", "Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Negotiating",
        "securityPackage": "APRIL Guarantee dd 26/04/21; APRIHL Guarantee dd 16/07/20",
        "guarantorList": ["APRIHL", "APRIL"],
    },
    {
        "bankName": "China Minsheng Banking Corp",
        "location": "HK",
        "borrower": "ASCH",
        "borrowerList": ["ASCH"],
        "dateOfFacility": "29/11/2022",
        "currency": "USD",
        "quantum": "57,000,000",
        "facilityType": "Trade Finance, Derivatives",
        "facilityTypeList": ["Trade Finance", "Derivatives"],
        "tenure": "5 years",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "Dah Sing Bank",
        "location": "HK",
        "borrower": "ASHK, ASCH",
        "borrowerList": ["ASHK", "ASCH"],
        "dateOfFacility": "21/11/2018, amended on 29/07/19, 20/03/24",
        "currency": "USD",
        "quantum": "20,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 14/12/18",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "E-Sun Bank",
        "location": "HK",
        "borrower": "ASHK",
        "borrowerList": ["ASHK"],
        "dateOfFacility": "02/04/2024",
        "currency": "USD",
        "quantum": "25,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 24/10/18",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "E-Sun Bank",
        "location": "HK",
        "borrower": "AFPT",
        "borrowerList": ["AFPT"],
        "dateOfFacility": "24/3/2024 amended on 27/06/25",
        "currency": "USD",
        "quantum": "25,000,000",
        "facilityType": "Trade Finance, Derivatives",
        "facilityTypeList": ["Trade Finance", "Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 24/07/24; DFF Guarantee dd 24/07/24",
        "guarantorList": ["APRIHL", "DFF"],
    },
    {
        "bankName": "Fubon Bank",
        "location": "HK",
        "borrower": "AIE, AFPT, IWC",
        "borrowerList": ["AIE", "AFPT", "IWC"],
        "dateOfFacility": "26/07/22 amended on 28/2/2025",
        "currency": "USD",
        "quantum": "50,000,000\n20,000,000",
        "facilityType": "Trade Finance, Derivatives",
        "facilityTypeList": ["Trade Finance", "Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 28/03/25; APRIHL Guarantee dd 28/03/25",
        "guarantorList": ["APRIHL", "APRIL"],
    },
    {
        "bankName": "Goldman Sachs International",
        "location": "HK",
        "borrower": "ASCH",
        "borrowerList": ["ASCH"],
        "dateOfFacility": "03/05/2018",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "N/A",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 19/02/18",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "Habib Bank Zurich (Hong Kong) Limited",
        "location": "HK",
        "borrower": "AFT",
        "borrowerList": ["AFT"],
        "dateOfFacility": "28/6/2022 amended on 07/05/25",
        "currency": "USD",
        "quantum": "7,640,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "PVHL Guarantee dd 28/02/22",
        "guarantorList": ["PVHL"],
    },
    {
        "bankName": "ICBC (Asia) Limited, Hong Kong",
        "location": "HK",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "05/03/2019",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 05/03/19",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "ICBC (Asia) Limited, Hong Kong",
        "location": "HK",
        "borrower": "ASCH",
        "borrowerList": ["ASCH"],
        "dateOfFacility": "04/04/2022",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "24/11/2024",
        "tenureExpired": True,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 04/04/22",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "ICBC (Asia) Limited, Hong Kong",
        "location": "HK",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "11/05/2021",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "ICBC (Asia) Limited, Hong Kong",
        "location": "HK",
        "borrower": "AIE, ASHK, GGTMCO",
        "borrowerList": ["AIE", "ASHK", "GGTMCO"],
        "dateOfFacility": "Negotiating",
        "currency": "USD",
        "quantum": "50,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Negotiating",
        "securityPackage": "APRIL Guarantee dd 23/11/21",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "ICBC, Jiangmen Xinhui",
        "location": "HK",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "09/02/2023",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "ICBC, Jiangmen Xinhui",
        "location": "HK",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "06/03/2024",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "5 years",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "ICBC, Jiangmen Xinhui",
        "location": "HK",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "29/05/2025",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "ICBC, Jiangmen Xinhui",
        "location": "HK",
        "borrower": "ASHK",
        "borrowerList": ["ASHK"],
        "dateOfFacility": "18/08/2022",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "ICBC, Jiangmen Xinhui",
        "location": "HK",
        "borrower": "ASHK",
        "borrowerList": ["ASHK"],
        "dateOfFacility": "09/05/2025",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "ICBC, Jiangmen Xinhui",
        "location": "HK",
        "borrower": "AFEM",
        "borrowerList": ["AFEM"],
        "dateOfFacility": "18/08/2022",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "ICBC, Jiangmen Xinhui",
        "location": "HK",
        "borrower": "AFEM",
        "borrowerList": ["AFEM"],
        "dateOfFacility": "29/05/2025",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "ICBC, Jiangmen Xinhui",
        "location": "HK",
        "borrower": "AFPT",
        "borrowerList": ["AFPT"],
        "dateOfFacility": "Negotiating",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Negotiating",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "ICBC, Jiangmen Xinhui",
        "location": "HK",
        "borrower": "AFPT",
        "borrowerList": ["AFPT"],
        "dateOfFacility": "Negotiating",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "10 years",
        "tenureExpired": False,
        "status": "Negotiating",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "ICICI Bank Limited",
        "location": "HK",
        "borrower": "ASCH",
        "borrowerList": ["ASCH"],
        "dateOfFacility": "06/12/2017",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 06/12/17",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "Industrial Bank Co., Ltd",
        "location": "HK",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "01/07/2025",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "Intesa Sanpaolo, Hong Kong",
        "location": "HK",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "11/12/2018 amended on 21/01/22",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "SGF Guarantee dd 01/10/24; APRIHL Guarantee dd 01/10/24",
        "guarantorList": ["APRIHL", "SGF"],
    },
    {
        "bankName": "Intesa Sanpaolo, Hong Kong",
        "location": "HK",
        "borrower": "ASCH, ASHK, IWC, AFPT, AIE",
        "borrowerList": ["ASCH", "ASHK", "IWC", "AFPT", "AIE"],
        "dateOfFacility": "10/12/2021, amended on 2/3/2022, further amended on 5/7/2022, renewed 10/10/2024",
        "currency": "USD",
        "quantum": "50,000,000",
        "facilityType": "Trade Finance, Derivatives",
        "facilityTypeList": ["Trade Finance", "Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 09/07/22",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "Intesa Sanpaolo, Hong Kong",
        "location": "HK",
        "borrower": "ASCH",
        "borrowerList": ["ASCH"],
        "dateOfFacility": "11/08/2015, amended on 26/06/2020",
        "currency": "EUR",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 25/08/25",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "Intesa Sanpaolo, Hong Kong",
        "location": "HK",
        "borrower": "AFPT",
        "borrowerList": ["AFPT"],
        "dateOfFacility": "21/08/2020",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Clean",
        "guarantorList": [],
    },
    {
        "bankName": "Maybank, Hong Kong",
        "location": "HK",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "23/7/2020, novated on 26/06/2023, further amended on 05/03/2024",
        "currency": "USD",
        "quantum": "5,000,000",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 14/11/19",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "Maybank, Hong Kong",
        "location": "HK",
        "borrower": "AIE, APRIL",
        "borrowerList": ["AIE", "APRIL"],
        "dateOfFacility": "28/10/2019, amended on 26/05/2020, 27/06/2023",
        "currency": "USD",
        "quantum": "30,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 14/11/19",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "Maybank, Hong Kong",
        "location": "HK",
        "borrower": "ASHK",
        "borrowerList": ["ASHK"],
        "dateOfFacility": "28/10/2019, amended on 26/05/2020, 21/06/2023, 02/01/2024, 22/02/2024 and 22/09/2025",
        "currency": "USD",
        "quantum": "20,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd 14/11/19",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "MUFG, Singapore",
        "location": "HK",
        "borrower": "ASCH",
        "borrowerList": ["ASCH"],
        "dateOfFacility": "Negotiating",
        "currency": "USD",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Negotiating",
        "securityPackage": "APRIL Guarantee",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "Nanyang Commercial Bank",
        "location": "HK",
        "borrower": "ASCH",
        "borrowerList": ["ASCH"],
        "dateOfFacility": "03/05/2023",
        "currency": "USD",
        "quantum": "11,150,000",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "Shanghai PuDong Development Bank, SG",
        "location": "HK",
        "borrower": "ASCH",
        "borrowerList": ["ASCH"],
        "dateOfFacility": "13/01/2023",
        "currency": "USD",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIL Guarantee dd  04/01/23",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "Taishin International Bank, Hong Kong",
        "location": "HK",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "31/1/2024 (ISDA dd 20/12/2018, amended on 01/03/24, 07/04/25)",
        "currency": "USD",
        "quantum": "80,000,000",
        "facilityType": "Trade Finance, Derivatives",
        "facilityTypeList": ["Trade Finance", "Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL + SGF Guarantee dd 23/01/25",
        "guarantorList": ["APRIHL", "SGF"],
    },
    # --- SG facilities ---
    {
        "bankName": "Arab Banking Corporation",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "20/12/2024",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 20/12/24",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "Arab Banking Corporation",
        "location": "SG",
        "borrower": "AIE, AFPT",
        "borrowerList": ["AIE", "AFPT"],
        "dateOfFacility": "Negotiating",
        "currency": "USD",
        "quantum": "10,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Negotiating",
        "tenureExpired": False,
        "status": "Negotiating",
        "securityPackage": "APRIL Guarantee",
        "guarantorList": ["APRIL"],
    },
    {
        "bankName": "BBVA, SG",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "22/04/2026",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 22/05/26",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "Bank of East Asia",
        "location": "SG",
        "borrower": "ASCH",
        "borrowerList": ["ASCH"],
        "dateOfFacility": "17/01/2023",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "Barclays Bank plc",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "14/03/2019, amended on 14/10/24",
        "currency": "USD",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 20/12/19",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "BNP Paribas",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "30/03/2026",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 30/03/26",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "China Construction Bank",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "04/02/2025",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "Nil",
        "guarantorList": [],
    },
    {
        "bankName": "Deutsche Bank",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "11/06/2024",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 11/06/2024",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "DZ Bank AG, Singapore Branch",
        "location": "SG",
        "borrower": "APRIL, AFPT, APPT, AFEM",
        "borrowerList": ["APRIL", "AFPT", "APPT", "AFEM"],
        "dateOfFacility": "21/04/2025",
        "currency": "USD",
        "quantum": "40,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 28/05/25; SGF Guarantee dd 28/05/25",
        "guarantorList": ["APRIHL", "SGF"],
    },
    {
        "bankName": "Emirates NBD",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "10/4/2023 amended on 15/05/25",
        "currency": "USD",
        "quantum": "30,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 14/04/23",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "Emirates NBD",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "18/10/2016, amended on 15/05/25",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 14/04/23",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "First Abu Dhabi Bank",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "26/03/2025",
        "currency": "USD",
        "quantum": "10,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 21/04/25",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "Mizuho",
        "location": "SG",
        "borrower": "AIE, AFBT, AFT",
        "borrowerList": ["AIE", "AFBT", "AFT"],
        "dateOfFacility": "Negotiating",
        "currency": "Negotiating",
        "quantum": "Negotiating",
        "facilityType": "Negotiating",
        "facilityTypeList": ["Negotiating"],
        "tenure": "Negotiating",
        "tenureExpired": False,
        "status": "Negotiating",
        "securityPackage": "Negotiating",
        "guarantorList": [],
    },
    {
        "bankName": "MUFG, Singapore",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "25/04/2022, amended on 15/03/2024",
        "currency": "USD",
        "quantum": "25,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 05/12/24; DFF Guarantee dd 05/12/24; SGF Guarantee dd 05/12/24",
        "guarantorList": ["APRIHL", "DFF", "SGF"],
    },
    {
        "bankName": "MUFG, Singapore",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "18/8/2021, amended on 05/12/24",
        "currency": "EUR",
        "quantum": "16,600,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 05/12/24; DFF Guarantee dd 05/12/24; SGF Guarantee dd 05/12/24",
        "guarantorList": ["APRIHL", "DFF", "SGF"],
    },
    {
        "bankName": "MUFG, Singapore",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "2/1/2019, amended on 30/12/2019, further amended on 30/12/2020, 05/12/24",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 05/12/24; DFF Guarantee dd 05/12/24; SGF Guarantee dd 05/12/24",
        "guarantorList": ["APRIHL", "DFF", "SGF"],
    },
    {
        "bankName": "MUFG, Singapore",
        "location": "SG",
        "borrower": "AIE, AFPT, AFT",
        "borrowerList": ["AIE", "AFPT", "AFT"],
        "dateOfFacility": "07/11/24 amended on 23/05/25",
        "currency": "USD",
        "quantum": "50,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 05/12/24; DFF Guarantee dd 05/12/24; SGF Guarantee dd 05/12/24",
        "guarantorList": ["APRIHL", "DFF", "SGF"],
    },
    {
        "bankName": "MUFG, India",
        "location": "SG",
        "borrower": "OCPL",
        "borrowerList": ["OCPL"],
        "dateOfFacility": "24/10/2024",
        "currency": "INR",
        "quantum": "1,450,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Negotiating",
        "tenureExpired": False,
        "status": "Negotiating",
        "securityPackage": "Negotiating",
        "guarantorList": [],
    },
    {
        "bankName": "MUFG, Jakarta",
        "location": "SG",
        "borrower": "RAPP",
        "borrowerList": ["RAPP"],
        "dateOfFacility": "31/01/2024",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 24/07/2019",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "MUFG, Malaysia",
        "location": "SG",
        "borrower": "AFEM, AFPT",
        "borrowerList": ["AFEM", "AFPT"],
        "dateOfFacility": "17/04/2017, amended on 19/06/2017, amended on 21/09/2018, amended on 16/06/2020, amended on 8/12/2021, further amended 11/03/2024",
        "currency": "USD",
        "quantum": "75,000,000",
        "facilityType": "Trade Finance",
        "facilityTypeList": ["Trade Finance"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL dd 24/09/24; DFF dd 24/09/24; SGF dd 24/09/24; MFF dd 24/09/24; SGF Guarantee dd 24/09/24",
        "guarantorList": ["APRIHL", "DFF", "MFF", "SGF"],
    },
    {
        "bankName": "Nomura Singapore Limited",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "09/07/2018, amended on 19/05/2020, further amended 19/11/24",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 31/01/25",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "Shanghai Pudong Bank, Singapore",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "12/2/2020, amended on 21/08/24",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 12/02/2020, amended on 21/08/24",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "Taishin International Bank, Singapore",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "21/02/2024",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 11/06/2024",
        "guarantorList": ["APRIHL"],
    },
    # --- UAE facilities ---
    {
        "bankName": "AIE",
        "location": "UAE",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "06/12/2024",
        "currency": "N/A",
        "quantum": "25,000,000",
        "facilityType": "Trade Financing",
        "facilityTypeList": ["Trade Financing"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 30/12/24; SGF Guarantee dd 30/12/24",
        "guarantorList": ["APRIHL", "SGF"],
    },
    {
        "bankName": "UBS, Singapore",
        "location": "SG",
        "borrower": "AIE",
        "borrowerList": ["AIE"],
        "dateOfFacility": "21/08/2024",
        "currency": "N/A",
        "quantum": "N/A",
        "facilityType": "Derivatives",
        "facilityTypeList": ["Derivatives"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "APRIHL Guarantee dd 21/08/2024",
        "guarantorList": ["APRIHL"],
    },
    {
        "bankName": "First Abu Dhabi Bank",
        "location": "UAE",
        "borrower": "AFPT",
        "borrowerList": ["AFPT"],
        "dateOfFacility": "02/09/2025",
        "currency": "USD",
        "quantum": "30,000,000",
        "facilityType": "Trade Financing",
        "facilityTypeList": ["Trade Financing"],
        "tenure": "Undefined",
        "tenureExpired": False,
        "status": "Current",
        "securityPackage": "AFPT Security over Movable Assets dd 02/09/25",
        "guarantorList": ["AFPT"],
    },
]

# ---------------------------------------------------------------------------
# BUILD DATAFRAME
# ---------------------------------------------------------------------------

df = pd.DataFrame(RAW_DATA)

# ---------------------------------------------------------------------------
# FILTER OPTIONS
# ---------------------------------------------------------------------------

BORROWERS = sorted({b for row in RAW_DATA for b in row["borrowerList"]})
BANKS = sorted({row["bankName"] for row in RAW_DATA})
FACILITY_TYPES = sorted({ft for row in RAW_DATA for ft in row["facilityTypeList"]})
GUARANTORS = sorted({g for row in RAW_DATA for g in row["guarantorList"]})

# ---------------------------------------------------------------------------
# DASH APP
# ---------------------------------------------------------------------------

app = dash.Dash(
    __name__,
    external_stylesheets=[dbc.themes.BOOTSTRAP],
    title="APRIL Bilateral Facilities Register",
)

def dropdown(id_, placeholder, options):
    return dbc.Col(
        [
            html.Label(placeholder, style={"fontWeight": "600", "fontSize": "0.82em",
                                           "textTransform": "uppercase", "letterSpacing": "0.5px"}),
            dcc.Dropdown(
                id=id_,
                options=[{"label": o, "value": o} for o in options],
                placeholder=f"All {placeholder}s",
                clearable=True,
                style={"fontSize": "0.92em"},
            ),
        ],
        md=4,
        className="mb-3",
    )


app.layout = dbc.Container(
    fluid=True,
    children=[
        # ---- HEADER ----
        html.Div(
            [
                html.H1("📊 APRIL Bilateral Facilities Register",
                        style={"fontWeight": "700", "letterSpacing": "1px"}),
                html.P("As at 02 June 2026 | Banking Facilities Overview across HK, SG & UAE",
                       style={"opacity": "0.85", "fontWeight": "300"}),
            ],
            style={
                "background": "linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #1565c0 100%)",
                "color": "white", "padding": "28px 40px", "textAlign": "center",
                "boxShadow": "0 4px 20px rgba(0,0,0,0.3)", "marginBottom": "16px",
            },
        ),

        # ---- STATS BAR ----
        dbc.Row(
            [
                dbc.Col(dbc.Card(dbc.CardBody([
                    html.Div(str(len(RAW_DATA)), id="total-count",
                             style={"fontSize": "1.8em", "fontWeight": "700", "color": "#0d47a1"}),
                    html.Div("Total Facilities", style={"fontSize": "0.8em", "color": "#546e7a",
                                                        "textTransform": "uppercase"}),
                ]), style={"borderLeft": "4px solid #1565c0", "background": "linear-gradient(135deg,#e3f2fd,#bbdefb)"}),
                width="auto", className="mb-2"),

                dbc.Col(dbc.Card(dbc.CardBody([
                    html.Div("72", id="filtered-count",
                             style={"fontSize": "1.8em", "fontWeight": "700", "color": "#0d47a1"}),
                    html.Div("Showing", style={"fontSize": "0.8em", "color": "#546e7a",
                                              "textTransform": "uppercase"}),
                ]), style={"borderLeft": "4px solid #1565c0", "background": "linear-gradient(135deg,#e3f2fd,#bbdefb)"}),
                width="auto", className="mb-2"),

                dbc.Col(dbc.Card(dbc.CardBody([
                    html.Div("0", id="expired-count",
                             style={"fontSize": "1.8em", "fontWeight": "700", "color": "#c62828"}),
                    html.Div("Expired", style={"fontSize": "0.8em", "color": "#546e7a",
                                              "textTransform": "uppercase"}),
                ]), style={"borderLeft": "4px solid #c62828", "background": "linear-gradient(135deg,#ffebee,#ffcdd2)"}),
                width="auto", className="mb-2"),

                dbc.Col(dbc.Card(dbc.CardBody([
                    html.Div("0", id="guarantee-count",
                             style={"fontSize": "1.8em", "fontWeight": "700", "color": "#0d47a1"}),
                    html.Div("Guarantees (Filtered)", style={"fontSize": "0.8em", "color": "#546e7a",
                                                             "textTransform": "uppercase"}),
                ]), style={"borderLeft": "4px solid #1565c0", "background": "linear-gradient(135deg,#e3f2fd,#bbdefb)"}),
                width="auto", className="mb-2"),
            ],
            justify="center", className="my-3 px-3",
        ),

        # ---- FILTER PANEL ----
        dbc.Card(
            dbc.CardBody([
                html.H5("🔍 Filter Facilities", style={"color": "#1a237e", "marginBottom": "16px"}),
                dbc.Row([
                    dropdown("filter-borrower", "Borrower", BORROWERS),
                    dropdown("filter-bank", "Bank", BANKS),
                    dropdown("filter-facility-type", "Facility Type", FACILITY_TYPES),
                    dropdown("filter-guarantor", "Guarantor", GUARANTORS),
                    dbc.Col([
                        html.Label("Guarantee / Security",
                                   style={"fontWeight": "600", "fontSize": "0.82em",
                                          "textTransform": "uppercase", "letterSpacing": "0.5px"}),
                        dcc.Dropdown(
                            id="filter-security",
                            options=[
                                {"label": "With Guarantee/Security", "value": "HAS_SECURITY"},
                                {"label": "No Guarantee/Security (Nil)", "value": "NO_SECURITY"},
                            ],
                            placeholder="All",
                            clearable=True,
                        ),
                    ], md=4, className="mb-3"),
                    dbc.Col([
                        html.Label("Tenure Status",
                                   style={"fontWeight": "600", "fontSize": "0.82em",
                                          "textTransform": "uppercase", "letterSpacing": "0.5px"}),
                        dcc.Dropdown(
                            id="filter-tenure",
                            options=[
                                {"label": "Expired Only", "value": "expired"},
                                {"label": "Non-Expired Only", "value": "active"},
                            ],
                            placeholder="All",
                            clearable=True,
                        ),
                    ], md=4, className="mb-3"),
                ]),
                html.Button("❌ Clear All Filters", id="clear-btn",
                            style={"background": "#c62828", "color": "white",
                                   "border": "none", "padding": "10px 28px",
                                   "borderRadius": "8px", "fontWeight": "600",
                                   "cursor": "pointer"}),
            ]),
            className="mb-3",
        ),

        # ---- GUARANTOR SUMMARY ----
        html.Div(id="guarantor-summary", style={"marginBottom": "16px"}),

        # ---- TABLE ----
        html.Div(id="facilities-table"),

        # ---- FOOTER ----
        html.Div(
            "APRIL Bilateral Facilities Register © 2026 — Data as at 02 June 2026",
            style={"textAlign": "center", "padding": "20px", "color": "#90a4ae", "fontSize": "0.82em"},
        ),
    ],
    style={"fontFamily": "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
           "background": "#f0f2f5", "minHeight": "100vh", "padding": "0"},
)


# ---------------------------------------------------------------------------
# CALLBACKS
# ---------------------------------------------------------------------------

@app.callback(
    [
        Output("filtered-count", "children"),
        Output("expired-count", "children"),
        Output("guarantee-count", "children"),
        Output("guarantor-summary", "children"),
        Output("facilities-table", "children"),
    ],
    [
        Input("filter-borrower", "value"),
        Input("filter-bank", "value"),
        Input("filter-facility-type", "value"),
        Input("filter-security", "value"),
        Input("filter-guarantor", "value"),
        Input("filter-tenure", "value"),
        Input("clear-btn", "n_clicks"),
    ],
)
def update_table(f_borrower, f_bank, f_facility, f_security, f_guarantor, f_tenure, _n):
    filtered = RAW_DATA.copy()

    if f_borrower:
        filtered = [r for r in filtered if f_borrower in r["borrowerList"]]
    if f_bank:
        filtered = [r for r in filtered if r["bankName"] == f_bank]
    if f_facility:
        filtered = [r for r in filtered if f_facility in r["facilityTypeList"]]
    if f_security == "HAS_SECURITY":
        filtered = [r for r in filtered
                    if r["securityPackage"] not in ("Nil", "N/A", "")]
    elif f_security == "NO_SECURITY":
        filtered = [r for r in filtered
                    if r["securityPackage"] in ("Nil", "N/A", "")]
    if f_guarantor:
        filtered = [r for r in filtered if f_guarantor in r["guarantorList"]]
    if f_tenure == "expired":
        filtered = [r for r in filtered if r["tenureExpired"]]
    elif f_tenure == "active":
        filtered = [r for r in filtered if not r["tenureExpired"]]

    n_filtered = len(filtered)
    n_expired = sum(1 for r in filtered if r["tenureExpired"])
    n_guarantees = sum(len(r["guarantorList"]) for r in filtered)

    # Guarantor summary block
    if f_guarantor:
        g_facilities = [r for r in filtered if f_guarantor in r["guarantorList"]]
        summary = dbc.Alert(
            [
                html.H5(f"{len(g_facilities)} guarantee(s) given by {f_guarantor}",
                        style={"color": "#e65100"}),
                html.Ul([
                    html.Li(f"{r['bankName']} — {r['borrower']} ({r['facilityType']})")
                    for r in g_facilities
                ]),
            ],
            color="warning",
        )
    else:
        summary = html.Div()

    # Build table rows
    if not filtered:
        table = dbc.Alert("No facilities match your current filters.", color="secondary",
                          style={"textAlign": "center"})
    else:
        loc_colors = {"HK": "#2e7d32", "SG": "#1565c0", "UAE": "#6a1b9a"}
        rows = []
        for i, r in enumerate(filtered):
            loc_color = loc_colors.get(r["location"], "#555")
            tenure_cell = r["tenure"]
            expired_badge = " ⚠ EXPIRED" if r["tenureExpired"] else ""
            row_style = {"background": "#fff3f3"} if r["tenureExpired"] else {}
            rows.append(
                html.Tr([
                    html.Td(i + 1),
                    html.Td(r["bankName"]),
                    html.Td(html.Span(r["location"],
                                     style={"background": loc_color, "color": "white",
                                            "padding": "2px 10px", "borderRadius": "10px",
                                            "fontSize": "0.78em", "fontWeight": "600"})),
                    html.Td(r["borrower"]),
                    html.Td(r["dateOfFacility"]),
                    html.Td(r["currency"]),
                    html.Td(r["quantum"]),
                    html.Td(r["facilityType"]),
                    html.Td([
                        tenure_cell,
                        html.Span(expired_badge,
                                  style={"background": "#c62828", "color": "white",
                                         "padding": "3px 10px", "borderRadius": "12px",
                                         "fontSize": "0.78em", "fontWeight": "700",
                                         "marginLeft": "6px"}) if r["tenureExpired"] else "",
                    ]),
                    html.Td(r["status"]),
                    html.Td(r["securityPackage"], style={"fontSize": "0.85em"}),
                ], style=row_style)
            )

        th_style = {
            "background": "linear-gradient(135deg, #1a237e, #1565c0)",
            "color": "white", "padding": "13px 14px",
            "fontWeight": "600", "fontSize": "0.82em",
            "textTransform": "uppercase", "letterSpacing": "0.5px",
            "whiteSpace": "nowrap",
        }
        thead = html.Thead(html.Tr([
            html.Th("#", style=th_style),
            html.Th("Bank", style=th_style),
            html.Th("Location", style=th_style),
            html.Th("Borrower(s)", style=th_style),
            html.Th("Date of Facility", style=th_style),
            html.Th("Currency", style=th_style),
            html.Th("Quantum", style=th_style),
            html.Th("Facility Type", style=th_style),
            html.Th("Tenure", style=th_style),
            html.Th("Status", style=th_style),
            html.Th("Security Package", style=th_style),
        ]))

        table = dbc.Card(
            html.Div(
                html.Table([thead, html.Tbody(rows)],
                           style={"width": "100%", "borderCollapse": "collapse",
                                  "fontSize": "0.88em"}),
                style={"overflowX": "auto"},
            ),
            style={"boxShadow": "0 2px 12px rgba(0,0,0,0.06)", "borderRadius": "12px"},
        )

    return str(n_filtered), str(n_expired), str(n_guarantees), summary, table


@app.callback(
    [
        Output("filter-borrower", "value"),
        Output("filter-bank", "value"),
        Output("filter-facility-type", "value"),
        Output("filter-security", "value"),
        Output("filter-guarantor", "value"),
        Output("filter-tenure", "value"),
    ],
    Input("clear-btn", "n_clicks"),
    prevent_initial_call=True,
)
def clear_filters(_):
    return None, None, None, None, None, None


# ---------------------------------------------------------------------------
# ENTRY POINT
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    app.run(debug=True)
